In [1]:
# use pandas library to load data
import pandas as pd
dataset = pd.read_csv('Heart_Disease_Prediction.csv')

# print the dataset size 
print('The size of dataset is: ', dataset.shape)

# get all variable in dataset 
all_var = dataset.columns.tolist()

# indicate X, Y 

ind_var = all_var[0:len(all_var)-1]
X = dataset[ind_var]
Y = dataset['Heart Disease'].values

#Split dataset into training and testing set (25%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.3)

# call algorithm: neural network
#from sklearn.neural_network import MLPClassifier
#model_nn = MLPClassifier(hidden_layer_sizes=(15,25,50))
#model_nn.fit(X_train,y_train)
#y_predict = model_nn.predict(X_test)

# call algorithm: Logistic regression
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression()
model_lg.fit(X_train,y_train)
y_predict = model_lg.predict(X_test)


# Keep the result is stable 
import numpy as np
np.random.seed(0)

# Show the accurracy of prediction 
from sklearn.metrics import accuracy_score
print ('Accuracy of Neural network is: %2.f'%(100*accuracy_score(y_predict,y_test)),'%')

# Show the confusion matrix   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print('The confusion matrix is: \n',cm)

# Show the classification report 
from sklearn.metrics import classification_report
print ('The report is: \n',classification_report(y_predict,y_test))



The size of dataset is:  (270, 14)
Accuracy of Neural network is: 81 %
The confusion matrix is: 
 [[43  7]
 [ 8 23]]
The report is: 
               precision    recall  f1-score   support

     Absence       0.86      0.84      0.85        51
    Presence       0.74      0.77      0.75        30

    accuracy                           0.81        81
   macro avg       0.80      0.80      0.80        81
weighted avg       0.82      0.81      0.82        81



/home/lnh/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
# use pandas library to load data
import pandas as pd
dataset = pd.read_csv('diabetes.csv')

# print the dataset size 
print('The size of dataset is: ', dataset.shape)

# get all variable in dataset 
all_var = dataset.columns.tolist()

# indicate X, Y 

ind_var = all_var[0:len(all_var)-1]
X = dataset[ind_var]

Y = dataset['Outcome'].values

#Split dataset into training and testing set (25%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.5)

# call algorithm: neural network
#from sklearn.neural_network import MLPClassifier
#model_nn = MLPClassifier(hidden_layer_sizes=(15,25,50))
#model_nn.fit(X_train,y_train)
#y_predict = model_nn.predict(X_test)

# call algorithm: Logistic regression
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression()
model_lg.fit(X_train,y_train)
y_predict = model_lg.predict(X_test)


# Keep the result is stable 
import numpy as np
np.random.seed(0)

# Show the accurracy of prediction 
from sklearn.metrics import accuracy_score
print ('Accuracy of Neural network is: %2.f'%(100*accuracy_score(y_predict,y_test)),'%')

# Show the confusion matrix   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print('The confusion matrix is: \n',cm)

# Show the classification report 
from sklearn.metrics import classification_report
print ('The report is: \n',classification_report(y_predict,y_test))



The size of dataset is:  (768, 9)


ValueError: Expected 2D array, got 1D array instead:
array=[342.   0. 210. 105.   0. 265.  90.   0.   0. 132. 304.   0.   0.   0.
   0.   0.   0. 237.  87.   0.  90.  63.   0.   0.   0.   0.   0.   0.
 127.   0. 100.   0.   0.   0.   0. 142. 122.   0. 185.   0.   0.   0.
 148. 180.   0.  53.  36. 392.   0.   0.   0.  71.   0.   0.   0. 180.
   0. 155. 274.  74. 326. 168.   0.   0.   0. 265.   0.   0.   0.   0.
 140.   0.   0. 205.   0.  95.   0.   0.   0.   0. 120. 122. 170. 478.
 125. 231.   0.  66. 100.   0.  74. 846.   0.   0. 116.   0.   0.  57.
   0.  72.   0. 210.   0. 225.   0. 210.  94.   0. 600. 112.   0.   0.
 230. 128.   0. 110.   0. 152.   0.   0.   0.  68.   0. 328. 145. 108.
 190. 165.   0.   0.   0.   0. 159.  90. 167.   0.   0.   0.   0.   0.
 100.  86.   0. 105.   0. 291.   0.  75.   0. 175.  76.   0.   0.   0.
   0.  84.   0. 100. 135.   0. 160.  50.  70. 152. 258.   0.  40. 200.
   0.  37.   0. 110.   0.  73.   0. 165. 318. 180. 120.   0. 215. 270.
  87. 166. 190. 540.   0. 440. 120. 155.   0.  76.   0.   0. 144.   0.
   0.   0.  45.   0. 146.   0. 129.   0.   0. 495.   0.   0.   0.   0.
   0. 106. 140. 321.   0. 220. 140. 156.   0. 170. 744. 185.  14.   0.
   0. 115. 135.   0. 155. 188.   0.   0. 325. 130.  29. 180. 402.  95.
   0.  41.  96. 120. 360.   0.   0.  64. 105.   0. 545.   0. 180.   0.
   0.  89. 168.   0.  57.   0.  23.  54.   0. 148.   0. 240.   0.   0.
   0.   0. 176.  77.   0.   0. 230.   0. 330.  64.  75. 168.   0.   0.
 215. 465.   0.  59.   0.  66. 115. 158.   0. 182.   0. 293.  48. 228.
 160.   0.  78.   0. 105.   0.  94.   0.   0.   0.   0.   0.   0.   0.
   0.  44.   0. 183.  88. 194.   0. 176.  71.   0.  51.  74. 110.   0.
   0.   0. 120.   0.  15. 285. 255.  45.   0.   0. 300. 178. 145. 110.
   0.  60.   0.   0.   0. 194.   0.  56.  76.  46.   0.  67.  49.   0.
 119.  70. 130. 220.  64.  85. 160.   0.   0.   0.   0. 510.  55.  71.
 106. 480.   0.   0. 115.   0.   0.  90. 120.   0. 116. 105.   0. 249.
 335. 180.   0.   0.   0.   0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [2]:
# use pandas library to load data
import pandas as pd
dataset = pd.read_csv('Heart_Disease_Prediction.csv')

# print the dataset size 
print('The size of dataset is: ', dataset.shape)

# get all variable in dataset 
all_var = dataset.columns.tolist()

# indicate X, Y 

ind_var = all_var[0:len(all_var)-1]
X = dataset[ind_var]
Y = dataset['Heart Disease'].values

#Split dataset into training and testing set (25%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.25)

# call algorithm: neural network
#from sklearn.neural_network import MLPClassifier
#model_nn = MLPClassifier(hidden_layer_sizes=(15,25,50))
#model_nn.fit(X_train,y_train)
#y_predict = model_nn.predict(X_test)

# call algorithm: Logistic regression
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression()
model_lg.fit(X_train,y_train)
y_predict = model_lg.predict(X_test)


# Keep the result is stable 
import numpy as np
np.random.seed(0)

# Show the accurracy of prediction 
from sklearn.metrics import accuracy_score
print ('Accuracy of Neural network is: %2.f'%(100*accuracy_score(y_predict,y_test)),'%')

# Show the confusion matrix   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print('The confusion matrix is: \n',cm)

# Show the classification report 
from sklearn.metrics import classification_report
print ('The report is: \n',classification_report(y_predict,y_test))



The size of dataset is:  (270, 14)
Accuracy of Neural network is: 84 %
The confusion matrix is: 
 [[33  7]
 [ 4 24]]
The report is: 
               precision    recall  f1-score   support

     Absence       0.82      0.89      0.86        37
    Presence       0.86      0.77      0.81        31

    accuracy                           0.84        68
   macro avg       0.84      0.83      0.84        68
weighted avg       0.84      0.84      0.84        68



/home/lnh/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [3]:
# use pandas library to load data
import pandas as pd
dataset = pd.read_csv('diabetes.csv')

# print the dataset size 
print('The size of dataset is: ', dataset.shape)

# get all variable in dataset 
all_var = dataset.columns.tolist()

# indicate X, Y 

ind_var = all_var[0:len(all_var)-1]
X = dataset[ind_var]
Y = dataset['Outcome'].values

#Split dataset into training and testing set (25%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.25)

# call algorithm: neural network
#from sklearn.neural_network import MLPClassifier
#model_nn = MLPClassifier(hidden_layer_sizes=(15,25,50))
#model_nn.fit(X_train,y_train)
#y_predict = model_nn.predict(X_test)

# call algorithm: Logistic regression
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression()
model_lg.fit(X_train,y_train)
y_predict = model_lg.predict(X_test)


# Keep the result is stable 
import numpy as np
np.random.seed(0)

# Show the accurracy of prediction 
from sklearn.metrics import accuracy_score
print ('Accuracy of Neural network is: %2.f'%(100*accuracy_score(y_predict,y_test)),'%')

# Show the confusion matrix   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print('The confusion matrix is: \n',cm)

# Show the classification report 
from sklearn.metrics import classification_report
print ('The report is: \n',classification_report(y_predict,y_test))



The size of dataset is:  (768, 9)
Accuracy of Neural network is: 79 %
The confusion matrix is: 
 [[115  15]
 [ 25  37]]
The report is: 
               precision    recall  f1-score   support

           0       0.88      0.82      0.85       140
           1       0.60      0.71      0.65        52

    accuracy                           0.79       192
   macro avg       0.74      0.77      0.75       192
weighted avg       0.81      0.79      0.80       192



/home/lnh/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# use pandas library to load data
import pandas as pd
dataset = pd.read_csv('Heart_Disease_Prediction.csv')

# print the dataset size 
print('The size of dataset is: ', dataset.shape)

# get all variable in dataset 
all_var = dataset.columns.tolist()

# indicate X, Y 

ind_var = all_var[0:len(all_var)-1]
X = dataset[ind_var]
Y = dataset['Heart Disease'].values

#Split dataset into training and testing set (25%)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size =0.25)

# call algorithm: neural network
#from sklearn.neural_network import MLPClassifier
#model_nn = MLPClassifier(hidden_layer_sizes=(15,25,50))
#model_nn.fit(X_train,y_train)
#y_predict = model_nn.predict(X_test)

# call algorithm: Logistic regression
from sklearn.linear_model import LogisticRegression
model_lg = LogisticRegression()

model_lg.fit(X_train,y_train)
y_predict = model_lg.predict(X_test)


# Keep the result is stable 
import numpy as np
np.random.seed(0)

# Show the accurracy of prediction 
from sklearn.metrics import accuracy_score
print ('Accuracy of Neural network is: %2.f'%(100*accuracy_score(y_predict,y_test)),'%')

# Show the confusion matrix   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print('The confusion matrix is: \n',cm)

# Show the classification report 
from sklearn.metrics import classification_report
print ('The report is: \n',classification_report(y_predict,y_test))

